apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000      # Service port
      targetPort: 3000 # Port your Java app listens on inside the pod
  type: NodePort  # Use LoadBalancer if you want to expose it externally
