apiVersion: v1
kind: Service
metadata:
  name: lms-be-service
spec:
  type: NodePort
  ports:
    - port: 3000               # The port that the service will expose
      targetPort: 3000         # The port the application listens on in the pod
      nodePort: 32100          # Optional: Specify the NodePort explicitly or let Kubernetes assign one
  selector:
    app: lms-be                # The label selector to target the correct pods
