apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "* * * * *"  # Adjust the cron schedule as needed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: ubuntu:latest  # Use a suitable Ubuntu image
              command: ["/bin/bash", "-c"]
              args:
                - |
                  apt-get update && \
                  apt-get install -y postgresql-client awscli && \
                  PGHOST=postgres-cluster-ip-service.default.svc.cluster.local && \
                  PGUSER=postgres && \
                  PGPASSWORD=$(cat /mnt/secrets/postgres-password) && \
                  pg_dumpall > /tmp/backup.sql && \
                  aws s3 cp /tmp/backup.sql s3://lms-appdata/backups/backup-$(date +%Y%m%d%H%M%S).sql
              volumeMounts:
                - name: postgres-secret-volume
                  mountPath: /mnt/secrets  # Path to mount the secret
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: postgres-secret-volume
              secret:
                secretName: postgres-secret  # Your secret containing the password
