apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "* * * * *"  # Runs at the top of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: amazonlinux:latest  # Image with necessary tools installed
              command: ["/bin/sh", "-c"]
              args:
                - |
                  yum install -y postgresql aws-cli && \  # Combined install command for efficiency
                  PGHOST=postgres-cluster-ip-service.default.svc.cluster.local && \
                  PGUSER=postgres && \
                  PGPASSWORD=$(cat /mnt/secrets/postgres-password) && \
                  pg_dumpall > /tmp/backup.sql && \
                  aws s3 cp /tmp/backup.sql s3://lms-appdata/backups/backup-$(date +%Y%m%d%H%M%S).sql
              volumeMounts:
                - name: postgres-secret-volume
                  mountPath: /mnt/secrets  # Path to mount the secret
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: postgres-secret-volume
              secret:
                secretName: postgres-secret  # Secret name for password
