apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data  # Path inside the pod
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: lms-db-pvc

# services file
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
