apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432      # PostgreSQL default port
      targetPort: 5432
  type: NodePort
