api: v1/app
kind: Deployment
metadata:
  name: database
  matchLabels: 
    app: database
spec:
  relicas:1
  selector:
    matchLabels: 
      app: database
  template:
    metadata:
      labels: 
        app: database
    spec:
      containers:
        - name: database
          image: postgres
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: password
