apiVersion: v1
kind: Service
metadata:
  name: lms-fe-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32101                # Port exposed by the service
  selector:
    app: lms-fe               # Selector to match the frontend pods
