apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Path on the node where data will be stored
